server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
jwt:
  secret: ${JWT_SECRET}

user:
  service:
    url: ${USER_SERVICE_URL}